### ISSUE TITLE
by-product-vulns error

### ISSUE THREAD

**Issue by darissimo** [Guezone/SECMON#17]
Hi, on page https://xx.xx.xx.xx/by-product-vulns I get this error:

 Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/flask_simplelogin/__init__.py", line 117, in simple_decorator
return dispatch(function, *args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/flask_simplelogin/__init__.py", line 98, in dispatch
return check(must) or fun(*args, **kwargs)
File "/var/www/secmon/secmon_web.py", line 587, in byProductVulns
product = request.form['product_selection']
File "/usr/lib/python3/dist-packages/werkzeug/datastructures.py", line 442, in __getitem__
raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

 Any suggestion?

**Comment by alb-uss** [comment]
Hello, does the problem appear with a specific product or all products?
